"""Complete integration test for all AI features."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from backend.api.main import app

REPO_ID = "01981d63-7bd7-459e-af26-d8a80617d499"


@pytest.fixture
def client() -> TestClient:
    """Create test client."""
    return TestClient(app)


def test_index_repository(client: TestClient):
    """Test indexing a repository."""
    response = client.post(f"/repositories/{REPO_ID}/index")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "completed"
    assert data["documents_indexed"] > 0
    print(f"\n✅ Indexed {data['documents_indexed']} documents")


def test_vector_search(client: TestClient):
    """Test vector search."""
    response = client.post(
        f"/repositories/{REPO_ID}/query",
        json={"query": "authentication", "retriever": "vector", "top_k": 5}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["total"] > 0
    assert len(data["results"]) > 0
    print(f"\n✅ Found {data['total']} vector search results")
    for i, result in enumerate(data['results'][:3], 1):
        print(f"  {i}. {result['file']} (score: {result['score']:.3f})")


def test_keyword_search(client: TestClient):
    """Test keyword search."""
    response = client.post(
        f"/repositories/{REPO_ID}/query",
        json={"query": "class", "retriever": "keyword", "top_k": 5}
    )
    assert response.status_code == 200
    data = response.json()
    # Keyword search may return 0 results if no exact matches
    assert "results" in data
    print(f"\n✅ Found {data['total']} keyword search results")


def test_hybrid_search(client: TestClient):
    """Test hybrid search."""
    response = client.post(
        f"/repositories/{REPO_ID}/query",
        json={"query": "Django", "retriever": "hybrid", "top_k": 5}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["total"] > 0
    print(f"\n✅ Found {data['total']} hybrid search results")


def test_ask_question(client: TestClient):
    """Test question answering (RAG)."""
    response = client.post(
        f"/repositories/{REPO_ID}/ask",
        json={"question": "What is the main purpose of this project?"}
    )
    assert response.status_code == 200
    data = response.json()
    assert len(data["answer"]) > 0
    assert len(data["sources"]) > 0
    print(f"\n✅ Generated answer ({len(data['answer'])} chars)")
    print(f"  Sources: {len(data['sources'])} documents")
    print(f"  Intent: {data['intent']}")
    print(f"  Latency: {data['total_latency_ms']:.2f}ms")


def test_graph_rag(client: TestClient):
    """Test GraphRAG query."""
    # First, extract relationships (required for GraphRAG)
    print("\n📊 Extracting relationships for GraphRAG...")
    extract_response = client.post(f"/repositories/{REPO_ID}/relationships")
    if extract_response.status_code == 200:
        extract_data = extract_response.json()
        print(f"  Extracted {extract_data.get('relationships_extracted', 0)} relationships")
    
    # Now query GraphRAG
    response = client.post(
        f"/repositories/{REPO_ID}/graph/query",
        json={"question": "What are the main components?"}
    )
    assert response.status_code == 200
    data = response.json()
    # GraphRAG returns nodes and edges, answer is generated by agent
    assert "retrieved_nodes" in data
    assert "retrieved_edges" in data
    print(f"\n✅ GraphRAG query successful")
    print(f"  Nodes: {data['total_nodes']}, Edges: {data['total_edges']}")


def test_crag(client: TestClient):
    """Test CRAG (Corrective RAG)."""
    response = client.post(
        f"/repositories/{REPO_ID}/crag/ask",
        json={"question": "How is authentication implemented?"}
    )
    assert response.status_code == 200
    data = response.json()
    assert len(data["answer"]) > 0
    print(f"\n✅ CRAG query successful")
    print(f"  Confidence: {data['confidence']:.2f}")
    print(f"  Valid: {data['answer_valid']}")


def test_execution_trace(client: TestClient):
    """Test that execution trace is populated."""
    response = client.post(
        f"/repositories/{REPO_ID}/ask",
        json={"question": "test"}
    )
    assert response.status_code == 200
    data = response.json()
    assert len(data["execution_trace"]) > 0
    print(f"\n✅ Execution trace has {len(data['execution_trace'])} steps")
    for step in data["execution_trace"][:3]:
        print(f"  - {step['node']}")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])